### ISSUE TITLE
iOS example project causes build errors on Windows when building Android

### ISSUE THREAD

**Issue by dpa99c** [Wizcorp/phonegap-plugin-wizUtils#18]
A symlink in the CordovaLib subproject of the iOS example project causes the Android build to fail on Windows when Cordova attempts to clone the plugin repo. Here's the console output containing the build error:

    Discovered plugin "phonegap-plugin-wizUtils" in config.xml. Adding it to the
    project
    Fetching plugin "https://github.com/Wizcorp/phonegap-plugin-wizUtils" via git clone
    Repository "https://github.com/Wizcorp/phonegap-plugin-wizUtils" checked out
    to git ref "master".
    Error: EEXIST: file already exists, symlink 'D:\Projects\iap_app\plugins\jp.wizcorp.phonegap.plugin.wizUtilsPlugin\example\ios\CordovaLib\Cordova.framework\Versions\A' -> 'D:\Work\Projects\Walks\App\iap_app\plugins\jp.wizcorp.phonegap.plugin.wizUtilsPlugin\example\ios\CordovaLib\Cordova.framework\Versions\Current'
        at Error (native)
        at Object.fs.symlinkSync (fs.js:1054:18)
        at cpdirSyncRecursive (G:\Users\dpa99_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\cp.js:76:10)
        at cpdirSyncRecursive (G:\Users\dpa99_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\cp.js:73:7)
        at cpdirSyncRecursive (G:\Users\dpa99_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\cp.js:73:7)
        at cpdirSyncRecursive (G:\Users\dpa99_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\cp.js:73:7)
        at cpdirSyncRecursive (G:\Users\dpa99_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\cp.js:73:7)
        at G:\Users\dpa99_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\cp.js:180:9
        at Array.forEach (native)
        at Object._cp (G:\Users\dpa99_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\cp.js:157:11)
    Warning: Command failed: cordova build android --release
     Use --force to continue.

cordova@6.4.0
cordova-android@6.1.0
npm@3.10.8
git@2.7.0
Windows 10 Pro x64

Maybe the example projects could be moved to a different repo?

**Comment by jrouault** [comment]
Hello,
Sadly we don't have a Windows environment to test your issue.
We started removing example projects from our other Cordova plugins but not yet for WizUtils. We will probably not have time to take care of that anytime soon.
If you find a fix and would be willing to send it as a PR that would be awesome.
